// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCSrqZAVNMiGGnUCooCg9p-sm8vZ6cu15I',
    appId: '1:684668751057:web:f9d2533f78962210ed09f0',
    messagingSenderId: '684668751057',
    projectId: 'todo1-f426a',
    authDomain: 'todo1-f426a.firebaseapp.com',
    storageBucket: 'todo1-f426a.appspot.com',
    measurementId: 'G-5BXYKS1J2R',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB-eofMhccfqsqJ3S1_UvLKx3CUGAN30pg',
    appId: '1:684668751057:android:6e949603ac82f0faed09f0',
    messagingSenderId: '684668751057',
    projectId: 'todo1-f426a',
    storageBucket: 'todo1-f426a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDAxBoo8EjEPDqKwKO3T-_sRZjB4TEMVy4',
    appId: '1:684668751057:ios:9bff5cd788260f7aed09f0',
    messagingSenderId: '684668751057',
    projectId: 'todo1-f426a',
    storageBucket: 'todo1-f426a.appspot.com',
    iosClientId: '684668751057-7ktps81f8kicdmiclandfb6l7dkr4p48.apps.googleusercontent.com',
    iosBundleId: 'com.example.todoApp2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDAxBoo8EjEPDqKwKO3T-_sRZjB4TEMVy4',
    appId: '1:684668751057:ios:9bff5cd788260f7aed09f0',
    messagingSenderId: '684668751057',
    projectId: 'todo1-f426a',
    storageBucket: 'todo1-f426a.appspot.com',
    iosClientId: '684668751057-7ktps81f8kicdmiclandfb6l7dkr4p48.apps.googleusercontent.com',
    iosBundleId: 'com.example.todoApp2',
  );
}
